// <auto-generated />
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241006011447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("API.ExoplanetData", b =>
                {
                    b.Property<string>("name")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<double>("parallax")
                        .HasColumnType("REAL");

                    b.Property<double>("x")
                        .HasColumnType("REAL");

                    b.Property<double>("y")
                        .HasColumnType("REAL");

                    b.Property<double>("z")
                        .HasColumnType("REAL");

                    b.HasKey("name");

                    b.ToTable("Exoplanets");
                });

            modelBuilder.Entity("API.StarData", b =>
                {
                    b.Property<string>("GAIA_id")
                        .HasMaxLength(19)
                        .HasColumnType("TEXT");

                    b.Property<double>("parallax")
                        .HasColumnType("REAL");

                    b.Property<double>("x")
                        .HasColumnType("REAL");

                    b.Property<double>("y")
                        .HasColumnType("REAL");

                    b.Property<double>("z")
                        .HasColumnType("REAL");

                    b.HasKey("GAIA_id");

                    b.ToTable("Stars");
                });
#pragma warning restore 612, 618
        }
    }
}
